Autocomplete support
ckaznocha/ide-go pull request #10
Opened 2018-01-03 01:39 UTC by pbitty

This adds autocomplete support, available in the latest version of [go-langserver](https://github.com/sourcegraph/go-langserver).

2018-01-03 03:13 UTC, ckaznocha requested changes
Thanks for the PR @pbitty this is great! I just had some pretty minor nit picks. I'm psyched to get this merged!

2018-01-03 03:13 UTC, ckaznocha commented on lib/ide-go.js
> +const AutocompleteAdapter = require('../node_modules/atom-languageclient/build/lib/adapters/autocomplete-adapter')
I'm not sure this is needed?

2018-01-03 03:13 UTC, ckaznocha commented on package.json
> +    "atom-languageclient": "^0.7.0",
I had another PR that updated the deps that I finally merged. Mind just pulling master into your branch?

2018-01-06 19:44 UTC, pbitty commented
@ckaznocha, changes addressed.

I have a [PR open](https://github.com/sourcegraph/go-langserver/pull/221) on `go-langserver` to add func snippets.  There are still some pieces to be decided.  If it is merged, there may be some tweaks needed to `ide-go` to support it:
* If the feature is disabled by default, a CLI flag will needed enable it
* If `InsertText` is not provided (because it is deprecated), it breaks snippet support.  I have a [PR open on atom-languageclient](https://github.com/atom/atom-languageclient/pull/165) to fix this

It could also end up being merged in a state that requires on changes here.  Either way, I am happy to submit a new PR depending on the outcome.

2018-01-06 20:19 UTC, ckaznocha approved these changes

2018-01-11 17:52 UTC, pbitty commented
@ckaznocha Will you be merging this soon?

sourcegraph/go-langserver#221 was merged in a way that does not require any changes here.  It will support autocomplete and along with func arg snippets.

2018-01-12 02:25 UTC, merged